spring:
  application:
    name: pricecheck
provider-a:
  active: true
  url: http://localhost:8081/api/provider-a/products/
provider-b:
  active: true
  url: http://localhost:8082/api/provider-b/products/